### ISSUE TITLE
Please update the dist binaries to 2.2.1

### ISSUE THREAD

**Issue by CollinChaffin** [ugetdm/uget-windows-installer#1]
And as for what you say in your blog of "Why SourceForge instead of GitHub?".......It is apparently so we can continue to deal with dead links to the DEV branch, and the usual nightmarish issues that anybody still stubborn enough to remain on SF is forced to deal with! :) :)

It would sure save everyone a LOT of headache to move the DEV efforts here to GH!

**Comment by slgobinath** [comment]
Hi,
Please note that new installer has been released: https://github.com/ugetdm/uget-windows-installer/releases/tag/v2.2.1
