### ISSUE TITLE
how to uget windows installer update to 2.2.2?

### ISSUE THREAD

**Issue by candrapersada** [ugetdm/uget-windows-installer#5]
uget 2.2.2 for windows installer? and how to use language indonesian for uget windows installer?

**Comment by CollinChaffin** [comment]
Bump - we really need the windows installer built for 2.2.2. TIA!

**Comment by jdrch** [comment]
Same request here.

**Comment by Droyk** [comment]
@slgobinath any updates?

**Comment by jdrch** [comment]
@Droyk The Windows installer has been "coming soon" for years now. Pretty sure it won't arrive at this rate.

If you want a similar `aria`-based FLOSS app with a Windows installer and Firefox + Chrome extensions, check out Persepolis.

**Comment by Droyk** [comment]
@jdrch I tried Persepolis & had a bad experience the app needs quite a lot of maintenance in both UX & UI department also video downloading seems half baked as well. I was looking for an alternative to IDM which I thought could've been uget coz of its great UI but it seems like it's not being maintained as often any alternatives you have?

**Comment by slgobinath** [comment]
Sorry guys. I was busy with other projects and my personal stuff.

Bumped the version to 2.2.3-1

Please check https://github.com/ugetdm/uget-windows-installer/releases/tag/v2.2.3-1

**Comment by jdrch** [comment]
@Droyk If you're looking for a media sniffer + download manager as DownThemAll once was, PDM isn't so good at that. But it uses `aria2` at the core and so the download acceleration feature works extremely well (much more reliable than DownThemAll, which often corrupted files.) The only problem I have with PDM is the Firefox extension often randomly reactivates download interception all on its own, even after the feature has been disabled. I filed a bug and it still hasn't been fixed (this seems to be PFTC for download managers 😉)

@slgobinath Understood. Unfortunately in the mean time Persepolis has become quite popular, uses `aria2` under the hood by default, and their Firefox extension has a higher rating too.

**Comment by slgobinath** [comment]
@jdrch its good to have alternatives.

I do like the experience Persepolis offers but I prefer uGet because it uses less memory. btw the Persepolis extension was forked from uGet extension ;-)

**Comment by jdrch** [comment]
> btw the Persepolis extension was forked from uGet extension ;-)

Yeah I thought I noticed some similarity there :)
